### ISSUE TITLE
[leetcode]l137. 只出现一次的数字 II

### ISSUE THREAD

**Issue by xiaowodi** [luluyuzhi/yuzhicode#85]
给你一个整数数组 nums ，除某个元素仅出现 一次 外，其余每个元素都恰出现 三次 。请你找出并返回那个只出现了一次的元素。

 

示例 1：

> 输入：nums = [2,2,3,2]
> 输出：3

示例 2：

> 输入：nums = [0,1,0,1,0,1,99]
> 输出：99

 

提示：

> 1 <= nums.length <= 3 * 104
> -231 <= nums[i] <= 231 - 1
> nums 中，除某个元素仅出现 一次 外，其余每个元素都恰出现 三次

 

> 进阶：你的算法应该具有线性时间复杂度。 你可以不使用额外空间来实现吗？

来源：力扣（LeetCode）
链接：https://leetcode-cn.com/problems/single-number-ii
著作权归领扣网络所有。商业转载请联系官方授权，非商业转载请注明出处。

**Comment by yuzhishuo** [comment]
```c++

x ^ 0 = x​;
x ^ 1 = ~x;
x & 0 = 0 ;
x & 1 = x;
```


[reduced method of a Karnaugh map](https://baike.baidu.com/item/%E5%8D%A1%E8%AF%BA%E5%9B%BE%E5%8C%96%E7%AE%80%E6%B3%95)
